export const STRIPE_CHECKOUT_REQUEST = 'STRIPE_CHECKOUT_REQUEST'
export const STRIPE_CHECKOUT_SUCCESS = 'STRIPE_CHECKOUT_SUCCESS'
export const STRIPE_CHECKOUT_FAIL = 'STRIPE_CHECKOUT_FAIL'

export const STRIPE_SESSION_DATA_REQUEST = 'STRIPE_SESSION_DATA_REQUEST'
export const STRIPE_SESSION_DATA_SUCCESS = 'STRIPE_SESSION_DATA_SUCCESS'
export const STRIPE_SESSION_DATA_FAIL = 'STRIPE_SESSION_DATA_FAIL'
